BOARD_SIZE = 5
EMPTY = 0
HIGH_GROUND = 9  
BUSH = 5         


HERO_ID = 1
ENEMY_ID = 2


HERO_MAX_HP = 25
HERO_DMG = 6
HERO_MOVE = 3
HERO_RANGE = 1


ORC_HP = 10
ORC_DMG = 3
ARCHER_HP = 8
ARCHER_DMG = 2
ARCHER_RANGE = 3
HEALER_HP = 12
HEALER_HEAL = 3
BOSS_HP = 40
BOSS_DMG = 8

HIGH_GROUND_DMG_BONUS = 2    
BUSH_DEFENSE_BONUS = 0.5     
BOSS_RAGE_THRESHOLD = 0.3    

AI_DEPTH = 3                 
INFINITY = 999999

W_HERO_HP = 2.0              
W_KILL_COUNT = 100.0         
W_HIGH_GROUND = 50.0         
W_BUSH_CONTROL = 20.0        
W_DISTANCE_PENALTY = 1.0     
W_BOSS_THREAT = 200.0        